# Get Google Gemini API Key from ai.google.dev

from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv

load_dotenv()

## WARNING: EACH CODE RUN COSTS GEMINI API CREDITS. GEMINI-2.5-FLASH HAS LIMITED FREE REQUESTS. GEMINI-2.5-PRO IS NOT FREE AT ALL
## WARNING: EACH CODE RUN COSTS GEMINI API CREDITS. GEMINI-2.5-FLASH HAS LIMITED FREE REQUESTS. GEMINI-2.5-PRO IS NOT FREE AT ALL
## WARNING: EACH CODE RUN COSTS GEMINI API CREDITS. GEMINI-2.5-FLASH HAS LIMITED FREE REQUESTS. GEMINI-2.5-PRO IS NOT FREE AT ALL
## WARNING: EACH CODE RUN COSTS GEMINI API CREDITS. GEMINI-2.5-FLASH HAS LIMITED FREE REQUESTS. GEMINI-2.5-PRO IS NOT FREE AT ALL
## WARNING: EACH CODE RUN COSTS GEMINI API CREDITS. GEMINI-2.5-FLASH HAS LIMITED FREE REQUESTS. GEMINI-2.5-PRO IS NOT FREE AT ALL
## WARNING: EACH CODE RUN COSTS GEMINI API CREDITS. GEMINI-2.5-FLASH HAS LIMITED FREE REQUESTS. GEMINI-2.5-PRO IS NOT FREE AT ALL
## WARNING: EACH CODE RUN COSTS GEMINI API CREDITS. GEMINI-2.5-FLASH HAS LIMITED FREE REQUESTS. GEMINI-2.5-PRO IS NOT FREE AT ALL

model = ChatGoogleGenerativeAI(model='gemini-2.5-flash')

## 

result = model.invoke("Write a poem in cricket")
print(result.content)